create table if not exists horarios_atendimento (
    id bigint generated by default as identity primary key,
    empresa_id bigint not null references empresas(id),
    dia_semana varchar(20) not null,
    ativo boolean not null default true,
    hora_inicio time,
    hora_fim time,
    intervalo_inicio time,
    intervalo_fim time,
    data_criacao timestamp not null default now(),
    data_atualizacao timestamp
);

alter table if exists horarios_atendimento
    drop constraint if exists uk_horarios_atendimento_empresa_dia;

alter table if exists horarios_atendimento
    add constraint uk_horarios_atendimento_empresa_dia unique (empresa_id, dia_semana);
