ALTER TABLE chamados
    ADD COLUMN IF NOT EXISTS origem VARCHAR(20) NOT NULL DEFAULT 'PAINEL';

UPDATE chamados
SET origem = CASE
    WHEN origem IS NULL OR TRIM(origem) = '' THEN 'PAINEL'
    WHEN UPPER(TRIM(origem)) IN ('MEU_GENDAZ', 'MEUGENDAZ', 'MEU GENDAZ') THEN 'MEU_GENDAZ'
    ELSE UPPER(TRIM(origem))
END;

ALTER TABLE chamados
    ALTER COLUMN origem DROP DEFAULT;
