ALTER TABLE clientes ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ATIVO';
UPDATE clientes SET status = COALESCE(status, 'ATIVO') WHERE status IS NULL;
ALTER TABLE clientes DROP CONSTRAINT IF EXISTS clientes_status_check;
ALTER TABLE clientes ADD CONSTRAINT clientes_status_check CHECK (status IN ('ATIVO', 'INATIVO', 'EXCLUIDO'));

ALTER TABLE servicos ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ATIVO';
UPDATE servicos SET status = COALESCE(status, 'ATIVO') WHERE status IS NULL;

ALTER TABLE profissionais ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ATIVO';
UPDATE profissionais SET status = COALESCE(status, 'ATIVO') WHERE status IS NULL;

ALTER TABLE conversas ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ABERTA';
UPDATE conversas SET status = COALESCE(status, 'ABERTA') WHERE status IS NULL;
