spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=60s

# AUMENTAR HEAP JVM
# POOL DE CONEXOES MAIS LEVE
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.leak-detection-threshold=60000

# AUMENTAR TIMEOUT DAS QUERIES
spring.jpa.properties.hibernate.jdbc.fetch_size=50
spring.jpa.properties.hibernate.jdbc.batch_size=20

# AGENDAMENTO SCHEDULING POOL SIZE
spring.task.scheduling.pool.size=1

